webtalk_init -webtalk_dir C:/Users/Patrick/Documents/TCNJ/senior_project_prep/vga_counter/vga_counter.sim/sim_1/behav/xsim/xsim.dir/tb_vga_counter_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun 24 21:09:53 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f2529e97-bfe7-484f-8d3d-25b2e3a6614e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "54b5f0f711c346e283d0aaadd3b90e1f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "65" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "960 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15376_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1011173236 -regid "" -xml C:/Users/Patrick/Documents/TCNJ/senior_project_prep/vga_counter/vga_counter.sim/sim_1/behav/xsim/xsim.dir/tb_vga_counter_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Patrick/Documents/TCNJ/senior_project_prep/vga_counter/vga_counter.sim/sim_1/behav/xsim/xsim.dir/tb_vga_counter_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Patrick/Documents/TCNJ/senior_project_prep/vga_counter/vga_counter.sim/sim_1/behav/xsim/xsim.dir/tb_vga_counter_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
